# Generated by Django 5.1.4 on 2024-12-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',), 'verbose_name': 'Автомобіль', 'verbose_name_plural': 'Автомобілі'},
        ),
    ]
