# Generated by Django 5.1.4 on 2024-12-25 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CAR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('user_last_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('user_phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Не вірний формат номеру')], verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('comment', models.CharField(max_length=300, null=True, verbose_name='Коментар')),
                ('user_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_model_auto', to='CAR.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Клієнта',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'user',
            },
        ),
    ]
