# Generated by Django 5.1.4 on 2024-12-26 10:16

import USERS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'клієнта', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_car',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_car_marka',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_car_model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[USERS.models.validate_ukrainian_phone_number], verbose_name='Номер телефону'),
        ),
    ]
