# Generated by Django 5.1.4 on 2024-12-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalСategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Додаткову категорію',
                'verbose_name_plural': 'Додаткові категорії',
                'db_table': 'addit_category',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=17, unique=True, verbose_name='Він код')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('brand_car', models.CharField(choices=[('jaguar', 'Jaguar'), ('volkswagen', 'Volkswagen'), ('jeep', 'Jeep'), ('lincoln', 'Lincoln'), ('dodge', 'Dodge'), ('infiniti', 'Infiniti'), ('kia', 'Kia'), ('hyundai', 'Hyundai'), ('acura', 'Acura'), ('chrysler', 'Chrysler'), ('nissan', 'Nissan'), ('bmw', 'BMW'), ('land_rover', 'Land Rover'), ('audi', 'Audi'), ('Honda', 'Honda')], max_length=150, verbose_name='Марка авто')),
                ('model_car', models.CharField(choices=[('Touareg', 'Touareg'), ('Cherokee KL 14-18', 'Cherokee KL 14-18'), ('Grand Cherokee 15 - 20', 'Grand Cherokee 15 - 20'), ('MKZ', 'MKZ'), ('Journey', 'Journey'), ('M 37', 'M 37'), ('Patriot', 'Patriot'), ('Magentis', 'Magentis'), ('Sonata LF (2014-2017)', 'Sonata LF (2014-2017)'), ('Optima JF (2016 - 2020)', 'Optima JF (2016 - 2020)'), ('Optima (2010 - 2015)', 'Optima (2010 - 2015)'), ('Sonata YF (2010-2014)', 'Sonata YF (2010-2014)'), ('Compass 17-20', 'Compass 17-20'), ('Jetta (2010 - 2017)', 'Jetta (2010 - 2017)'), ('Q 50', 'Q 50'), ('Grand Cherokee 10-14', 'Grand Cherokee 10-14'), ('MDX', 'MDX'), ('200', '200'), ('Sonata New Rise (2017 - 2019)', 'Sonata New Rise (2017 - 2019)'), ('Passat B8 USA', 'Passat B8 USA'), ('Passat B7 USA', 'Passat B7 USA'), ('Murano', 'Murano'), ('Maxima A36', 'Maxima A36'), ('XF X250/X260', 'XF X250/X260'), ('Compass 11-16', 'Compass 11-16'), ('E60/E61', 'E60/E61'), ('CC', 'CC'), ('QX60', 'QX60'), ('Range Rover Evoque L538', 'Range Rover Evoque L538'), ('a4', 'a4'), ('a6', 'a6'), ('Cherokee KL 18-23', 'Cherokee KL 18-23'), ('Renegade', 'Renegade'), ('Discovery Sport L550', 'Discovery Sport L550'), ('Durango', 'Durango'), ('CRV', 'CRV'), ('F-Pace X761', 'F-Pace X761'), ('X5 G05', 'X5 G05'), ('Range Rover L405', 'Range Rover L405'), ('7 series  G 11/12', '7 series  G 11/12'), ('Range Rover Sport L494', 'Range Rover Sport L494'), ('Range Rover Evoque L551', 'Range Rover Evoque L551'), ('Discovery 5 L462', 'Discovery 5 L462'), ('Range Rover Velar L560', 'Range Rover Velar L560'), ('Discovery 4 L319', 'Discovery 4 L319'), ('Rogue T32', 'Rogue T32'), ('X5 F15', 'X5 F15'), ('I-Pace X590', 'I-Pace X590'), ('Range Rover Sport L320', 'Range Rover Sport L320'), ('Santa Fe', 'Santa Fe')], max_length=150, verbose_name='Модель авто')),
                ('year', models.PositiveIntegerField(choices=[(2013, '2013'), (2012, '2012'), (2014, '2014'), (2017, '2017'), (2015, '2015'), (2008, '2008'), (2016, '2016'), (2019, '2019'), (2018, '2018'), (2020, '2020'), (2011, '2011'), (2005, '2005'), (2010, '2010'), (2002, '2002')], verbose_name='Рік випуску')),
                ('engine_volume', models.DecimalField(choices=[(3, '3'), (2.4, '2.4'), (3.6, '3.6'), (3.7, '3.7'), (2, '2'), (3.5, '3.5'), (1.8, '1.8'), (2.5, '2.5'), (2.2, '2.2'), (5.7, '5.7'), (1.4, '1.4')], decimal_places=1, max_digits=4, verbose_name="Об'єм двигуна")),
                ('fueld_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро')], max_length=100, verbose_name='Вид топлива')),
                ('transmission', models.CharField(choices=[('8akpp', '8 АКПП'), ('akpp', 'АКПП'), ('varaable', 'Варіатор')], max_length=50, verbose_name='КПП')),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('svu', 'Позашляховик'), ('station_wagon', 'Універсал')], max_length=100, verbose_name='Кузов')),
                ('features', models.TextField(choices=[('tdi', 'TDI'), ('turbo_gasoline', 'Турбобензин'), ('gasoline', 'Бензин'), ('turbo_diesel', 'Турбодизель'), ('fsi', 'FSI'), ('tfsi', 'TFSI'), ('tsi', 'TSI')], max_length=50, verbose_name='Особливості')),
                ('color', models.CharField(choices=[('grey', 'Сірий'), ('black', 'Чорний'), ('shinee_grey', 'Срібний'), ('white', 'Білий'), ('red', 'Червоний'), ('orange', 'Помаранчовий'), ('brown', 'Коричневий'), ('blue', 'Синій'), ('gold', 'Золотий'), ('bordo', 'Бордовий'), ('green', 'Зелений')], max_length=50, verbose_name='Колір')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car_image', verbose_name='Фото авто')),
            ],
            options={
                'verbose_name': 'Автомомбіль',
                'verbose_name_plural': 'Автомобілі',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Підкатегорія')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорію',
                'verbose_name_plural': 'Підкатегорії',
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_code', models.CharField(max_length=50, unique=True, verbose_name='Оригінальний номер запчастини')),
                ('name', models.CharField(max_length=150, verbose_name='Назва запчастини')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('sku', models.PositiveIntegerField(unique=True, verbose_name='Артикул')),
                ('warehouse', models.CharField(choices=[('swarehouse_korea', 'Склад Корея'), ('swarehouse_wag', 'Склад Wag'), ('swarehouse_return', 'Повернення'), ('swarehouse_reserv', 'В резерві')], max_length=100, verbose_name='Склад')),
                ('cell', models.PositiveIntegerField(null=True, verbose_name='Ячейка')),
                ('condition', models.CharField(choices=[('new', 'Нова'), ('living', 'Б\\У')], max_length=50, verbose_name='Стан')),
                ('availability', models.CharField(choices=[('in_stock', 'В наявності'), ('shipped', 'Відправлено'), ('returned', 'Повернення'), ('defective', 'Брак'), ('written_off', 'Списано')], default='in_stock', max_length=50, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spare_parts', verbose_name='Фото')),
                ('additional_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.additionalсategory', verbose_name='Дод.категорія')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.car', verbose_name='Автомобіль')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.categories', verbose_name='Категорія')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.subcategory', verbose_name='Підкатегорія')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'db_table': 'spare_part',
            },
        ),
        migrations.AddField(
            model_name='additionalсategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.subcategory', verbose_name='Підкатегорія'),
        ),
    ]
