# Generated by Django 5.1.4 on 2024-12-19 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',), 'verbose_name': 'Автомомбіль', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ('id',), 'verbose_name': 'Запчастина', 'verbose_name_plural': 'Запчастини'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='photo',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='GOODS.car', verbose_name='Автомобіль'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='car_image/')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GOODS.car')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='spare_parts/')),
                ('spareparts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GOODS.sparepart')),
            ],
        ),
    ]
