# Generated by Django 5.1.4 on 2024-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='additional_condition',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True, verbose_name='Додаткова умова'),
        ),
    ]
