# Generated by Django 4.2.7 on 2024-12-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOODS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalСategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Додаткову категорію',
                'verbose_name_plural': 'Додаткові категорії',
                'db_table': 'addit_category',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=17, unique=True, verbose_name='Він коде')),
                ('body_type', models.CharField(max_length=100, verbose_name='Кузов')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=4, verbose_name="Об'єм двигуна")),
                ('fueld_type', models.CharField(max_length=100, verbose_name='Вид топлива')),
                ('features', models.TextField(blank=True, verbose_name='Особливосты')),
                ('transmission', models.CharField(max_length=50, verbose_name='КПП')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('country_of_origin', models.CharField(max_length=100, verbose_name='Країна походження')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car_image', verbose_name='Фото авто')),
            ],
            options={
                'verbose_name': 'Автомомбіль',
                'verbose_name_plural': 'Автомобілі',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка авто')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Модель авто')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOODS.carbrand', verbose_name='Марка авто')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_code', models.CharField(max_length=50, unique=True, verbose_name='Оригінальний номер запчастини')),
                ('name', models.CharField(max_length=150, verbose_name='Назва запчастини')),
                ('condition', models.CharField(max_length=50, verbose_name='Стан')),
                ('availability', models.CharField(choices=[('in_stock', 'В наявності'), ('shipped', 'Відправлено'), ('returned', 'Повернення'), ('defective', 'Брак'), ('written_off', 'Списано')], default='in_stock', max_length=50, verbose_name='Наявно')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spare_parts', verbose_name='Фото')),
                ('additional_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.additionalсategory', verbose_name='Дод.категорія')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOODS.car', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'db_table': 'spare_part',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Підкатегорія')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Підкатегорію',
                'verbose_name_plural': 'Підкатегорії',
                'db_table': 'sub_category',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='GOODS.categories', verbose_name='Категорія'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOODS.categories', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.categories', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOODS.subcategory', verbose_name='Підкатегорія'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOODS.carbrand', verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_by_model', to='GOODS.carmodel', verbose_name='Модель авто'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_by_year', to='GOODS.carmodel', verbose_name='Рік випуску'),
        ),
        migrations.AddField(
            model_name='additionalсategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOODS.subcategory', verbose_name='Підкатегорія'),
        ),
    ]
