# Generated by Django 4.2.7 on 2024-12-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOODS', '0002_additionalсategory_car_carbrand_carmodel_sparepart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Бренд авто', 'verbose_name_plural': 'Бренди авто'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель авто', 'verbose_name_plural': 'Моделі авто'},
        ),
        migrations.AlterModelTable(
            name='carbrand',
            table='car_brand',
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table='car_model',
        ),
    ]
