# Generated by Django 5.1.4 on 2024-12-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONTENT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newandblog',
            options={'verbose_name': 'Новину', 'verbose_name_plural': 'Новини'},
        ),
    ]
