# Generated by Django 5.1.4 on 2024-12-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTENT', '0002_alter_newandblog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carоntheroadimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagess', to='CONTENT.carоntheroad'),
        ),
    ]
