# Generated by Django 5.1.4 on 2024-12-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CAR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalСategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Додаткову категорію',
                'verbose_name_plural': 'Додаткові категорії',
                'db_table': 'addit_category',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_code', models.CharField(max_length=50, verbose_name='Оригінальний номер запчастини')),
                ('name', models.CharField(max_length=150, verbose_name='Назва запчастини')),
                ('warehouse', models.CharField(choices=[('swarehouse_korea', 'Склад Корея'), ('swarehouse_wag', 'Склад Wag'), ('swarehouse_return', 'Повернення'), ('swarehouse_reserv', 'В резерві')], max_length=100, verbose_name='Склад')),
                ('cell', models.PositiveIntegerField(null=True, verbose_name='Ячейка')),
                ('condition', models.CharField(choices=[('new', 'Нова'), ('living', 'Вживана')], default='living', max_length=50, verbose_name='Стан')),
                ('additional_condition', models.CharField(blank=True, choices=[('good', 'Хороший'), ('satisfactory', 'Задовільний'), ('defective', 'З дефектом'), ('repaired', 'Зі слідами ремонту')], max_length=50, null=True, verbose_name='Додаткова умова')),
                ('availability', models.CharField(choices=[('in_stock', 'В наявності'), ('shipped', 'Відправлено'), ('returned', 'Повернення'), ('defective', 'Брак'), ('written_off', 'Списано')], default='in_stock', max_length=50, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул')),
                ('additional_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPARE.additionalсategory', verbose_name='Дод.категорія')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='CAR.car', verbose_name='Автомобіль')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPARE.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'db_table': 'spare_part',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='spare_parts/')),
                ('spareparts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='SPARE.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Підкатегорія')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPARE.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорію',
                'verbose_name_plural': 'Підкатегорії',
                'db_table': 'sub_category',
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPARE.subcategory', verbose_name='Підкатегорія'),
        ),
        migrations.AddField(
            model_name='additionalсategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPARE.subcategory', verbose_name='Підкатегорія'),
        ),
    ]
